### ISSUE TITLE
Original work

### ISSUE THREAD

**Issue by a635725626** [amanjeetsahu/Natural-Language-Processing-Specialization#1]
Excuse me, Could u please upload the original version of this work? cuz I want to do it myself, thx!

**Comment by amanjeetsahu** [comment]
Sorry But what exactly are you trying to say all the original Assignment work has been pushed.

**Comment by a635725626** [comment]
> 
> 
> Okay, Gotcha! Let me see If I can reset the workspace in Coursera and download the original version.

thx very much

**Comment by amanjeetsahu** [comment]
Updated the Original Assignment Files.
