### ISSUE TITLE
C2-W4 : back_prop & gradient_descent

### ISSUE THREAD

**Issue by shiinalight** [amanjeetsahu/Natural-Language-Processing-Specialization#8]
some of my tests fail in these two problems and therefore I cannot pass this 
could you please take a look?
[C2_W4_Assignment.pdf](https://github.com/amanjeetsahu/Natural-Language-Processing-Specialization/files/12448277/C2_W4_Assignment.pdf)

**Comment by MistHunter24** [comment]
Hello,
At a first glance, in  UNQ_C4 there is a difference in the code you wrote vs the  grad_b1 and grad_b2 that use np.sum(...) from [here](https://github.com/amanjeetsahu/Natural-Language-Processing-Specialization/blob/master/Natural%20Language%20Processing%20with%20Probabilistic%20Models/Week%204/C2_W4_Assignment_Solution.ipynb)
After that,  UNQ_C5 uses the back_prop function.

**Comment by shiinalight** [comment]
Hello,
First of all thanks for taking time for my code;
your help is really appreciated
I tried multiple times yesterday to apply what you said but I got more tests failed or other errors
just if you had the time and have access to the Coursera related lab would you correct it on the file and resend it; I'm so sorry for asking it just if you had the time and felt like it, if not it is perfectly ok

**Comment by MistHunter24** [comment]
Hello,
I am not very good at this, but I will gladly take a look.  I lost access to the course a while ago could you also attach the  w4_unittest file? The version I am using does not use unittests so I cannot validate the final output.

**Comment by shiinalight** [comment]
https://github.com/shiinalight/NLP-labs/blob/main/C2_W4_Assignment.ipynb
Does this work? or if what you need is sth else can you provide me where should I get it for you?

**Comment by MistHunter24** [comment]
If you open the assignment from coursera, you will have access to the project file structure(somewhere on the upper right side in the menus). Inside you should be able to locate the unit tests.

**Comment by shiinalight** [comment]
Here you go sorry for the wrong file


[w4_unittest.py.zip](https://github.com/amanjeetsahu/Natural-Language-Processing-Specialization/files/12468431/w4_unittest.py.zip)

**Comment by MistHunter24** [comment]
ok, so what I found so far is this. 
in exercise 04:
If you want to allow negative values in the output of the ReLU activation function, you should not apply the ReLU activation to the l1 values used to compute the gradient of the bias vector b1. meaning that you should delete or comment
`l1[l1 < 0] = 0`

in exercise 05, I am missing a file, but I guess that fixing the _back_prop()_ fixed the tests.
I get: FileNotFoundError: [Errno 2] No such file or directory: './support_files/gradient_descent/w1.pkl'

let me know if this works

**Comment by shiinalight** [comment]
Man, you really saved meeeee!! I cannot believe to be so lucky that my issue came across you 
I donno how to appreciate you 😭🙌🏻 I am self learner so, when I confront bugs there's no one around to ask for help. 
I wish I get good some day and help ppl the way you did for me 🫠
